version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - wget https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
      - unzip terraform_1.11.2_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Creating S3 bucket and DynamoDB table if they don't exist"
      - aws s3 mb s3://${STATE_FILE_BUCKET} --region ${REGION} || echo "Bucket already exists"
      - aws s3api put-bucket-versioning --bucket ${STATE_FILE_BUCKET} --versioning-configuration Status=Enabled || echo "Versioning already enabled"
      - aws dynamodb create-table --table-name ${DB_TABLE} --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST --region ${REGION} || echo "Table already exists"
      - cd root-module
      - terraform init -backend-config="bucket=${STATE_FILE_BUCKET}" -backend-config="key=${STATE_FILE_PATH}" -backend-config="region=${REGION}" -backend-config="encrypt=true" -backend-config="dynamodb_table=${DB_TABLE}"
  build:
    commands:
      - echo 'environment = "usdev-usw2"' > ../usdev-usw2.tfvars
      - echo 'project_name = "alr"' >> ../usdev-usw2.tfvars
      - echo 'application_name = "alr-mobile"' >> ../usdev-usw2.tfvars
      - echo 'module_name = "alr-be"' >> ../usdev-usw2.tfvars
      - echo 'vpc_cidr = "10.0.0.0/16"' >> ../usdev-usw2.tfvars
      - echo 'public_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]' >> ../usdev-usw2.tfvars
      - echo 'private_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]' >> ../usdev-usw2.tfvars
      - echo 'container_port = 80' >> ../usdev-usw2.tfvars
      - echo 'container_cpu = 256' >> ../usdev-usw2.tfvars
      - echo 'container_memory = 512' >> ../usdev-usw2.tfvars
      - echo 'desired_count = 1' >> ../usdev-usw2.tfvars
      - cat ../usdev-usw2.tfvars
      - terraform plan -var-file="../usdev-usw2.tfvars" -out=tfplan
artifacts:
  files:
    - "**/*"