version: 0.2

env:
  variables:
    TF_VERSION: "1.5.7"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_install.zip
      - mv terraform /usr/bin/
      - terraform --version

  pre_build:
    commands:
      - |
        if [ -z "$ENVIRONMENT" ]; then
          case "$CODEBUILD_WEBHOOK_HEAD_REF" in
            "refs/heads/develop") export ENVIRONMENT="usdev-usw2" ;;
            "refs/heads/main") export ENVIRONMENT="usqa-usw2" ;;
            "refs/heads/release") export ENVIRONMENT="usprod-usw2" ;;
            *) export ENVIRONMENT="usdev-usw2" ;;
          esac
        fi
      - echo "=== ALR Infrastructure Pipeline ($ENVIRONMENT-alr-infra) ==="
      - echo "Deploying to environment: $ENVIRONMENT"
      - terraform init -backend-config="backend-configs/$ENVIRONMENT.hcl" -reconfigure
      - terraform validate

  build:
    commands:
      - |
        if [ "$TF_COMMAND" = "plan" ]; then
          terraform plan -var-file="environments/$ENVIRONMENT.tfvars" -out=tfplan
        elif [ "$TF_COMMAND" = "apply" ]; then
          terraform apply -var-file="environments/$ENVIRONMENT.tfvars" -auto-approve
        else
          echo "Unknown command: $TF_COMMAND"
          exit 1
        fi

  post_build:
    commands:
      - echo "=== ALR Infrastructure Pipeline Completed ==="
      - echo "Pipeline: $ENVIRONMENT-alr-infra"
      - echo "Terraform $TF_COMMAND completed successfully"

artifacts:
  files:
    - tfplan
    - "**/*"