version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_install.zip
      - mv terraform /usr/bin/
      - terraform --version
      - echo "Installing Docker..."
      - yum update -y
      - yum install -y docker
      - service docker start || true
      - docker --version
      
  pre_build:
    commands:
      - echo "Terraform init and validate..."
      - cd $CODEBUILD_SRC_DIR
      - export AWS_REGION=us-west-2
      - terraform init -reconfigure
      - terraform validate
      
  build:
    commands:
      - echo "Running Terraform $TF_COMMAND..."
      - if [ "$TF_COMMAND" = "plan" ]; then terraform plan -out=tfplan; fi
      - if [ "$TF_COMMAND" = "apply" ]; then terraform apply -auto-approve; fi
      - if [ "$TF_COMMAND" = "destroy" ]; then terraform destroy -auto-approve; fi
      
  post_build:
    commands:
      - echo "Terraform $TF_COMMAND completed on `date`"

artifacts:
  files:
    - tfplan
    - terraform.tfstate
  discard-paths: yes