version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/bin/
      - terraform --version

  pre_build:
    commands:
      - terraform init -backend-config="backend-configs/$ENVIRONMENT.hcl" -reconfigure
      - terraform validate

  build:
    commands:
      - terraform plan -var-file="environments/$ENVIRONMENT.tfvars" -out=tfplan

artifacts:
  files:
    - tfplan