version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - wget https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
      - unzip terraform_1.11.2_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "=== DEBUGGING FILE STRUCTURE ==="
      - pwd
      - ls -la
      - echo "=== LOOKING FOR TFVARS FILES ==="
      - find . -name "*.tfvars" -ls
      - echo "=== CHECKING SPECIFIC DIRECTORIES ==="
      - ls -la tfvars-file/ || echo "tfvars-file directory not found"
      - ls -la environments/ || echo "environments directory not found"
      - echo "=== MOVING TO ROOT-MODULE ==="
      - cd root-module
      - pwd
      - ls -la
      - terraform init -backend-config="bucket=${STATE_FILE_BUCKET}" -backend-config="key=${STATE_FILE_PATH}" -backend-config="region=${REGION}" -backend-config="encrypt=true" -backend-config="dynamodb_table=${DB_TABLE}"
  build:
    commands:
      - echo "=== FINDING TFVARS FILE ==="
      - find .. -name "*.tfvars" -ls
      - TFVARS_PATH=$(find .. -name "*.tfvars" | head -1)
      - echo "Found tfvars at $TFVARS_PATH"
      - test -f "$TFVARS_PATH" && echo "File exists" || echo "File does not exist"
      - terraform plan -var-file="$TFVARS_PATH" -out=tfplan
artifacts:
  files:
    - "**/*"