version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - wget https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
      - unzip terraform_1.11.2_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Environment variables:"
      - echo "ENVIRONMENT=${ENVIRONMENT}"
      - echo "STATE_FILE_BUCKET=${STATE_FILE_BUCKET}"
      - echo "STATE_FILE_PATH=${STATE_FILE_PATH}"
      - ls -la
      - find . -name "*.tfvars"
      - cd root-module
      - terraform init -backend-config="bucket=${STATE_FILE_BUCKET}" -backend-config="key=${STATE_FILE_PATH}" -backend-config="region=${REGION}" -backend-config="encrypt=true" -backend-config="dynamodb_table=${DB_TABLE}"

  build:
    commands:
      - echo "Finding tfvars file dynamically"
      - TFVARS_FILE=$(find .. -name "usdev-usw2.tfvars" -type f | head -1)
      - echo "Found tfvars file: $TFVARS_FILE"
      - test -f "$TFVARS_FILE" && echo "File exists" || echo "File not found"
      - terraform plan -var-file="$TFVARS_FILE" -out=tfplan

artifacts:
  files:
    - "**/*"