version: 0.2

env:
  variables:
    TF_VERSION: "1.5.7"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_install.zip
      - mv terraform /usr/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Environment is $ENVIRONMENT"
      - echo "TF Command is $TF_COMMAND"
      - terraform init -backend-config="backend-configs/$ENVIRONMENT.hcl" -reconfigure
      - terraform validate

  build:
    commands:
      - echo "Running terraform $TF_COMMAND"
      - terraform $TF_COMMAND -var-file="environments/$ENVIRONMENT.tfvars" -out=tfplan

  post_build:
    commands:
      - echo "Terraform completed successfully"

artifacts:
  files:
    - tfplan
    - "**/*"