# ALR Subscription Microservice - Infrastructure Pipeline Buildspec
# Pipeline: ${ENVIRONMENT}-alr-infra
version: 0.2

env:
  variables:
    TF_VERSION: "1.5.7"
    AWS_DEFAULT_REGION: "us-west-2"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== ALR Infrastructure Pipeline - Installing Dependencies ==="
      - echo "Installing Terraform $TF_VERSION..."
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_install.zip
      - mv terraform /usr/bin/
      - terraform --version
      - echo "Terraform installation completed"
      
  pre_build:
    commands:
      - echo "=== ALR Infrastructure Pipeline - Pre-build Phase ==="
      - cd $CODEBUILD_SRC_DIR
      - echo "Environment: $ENVIRONMENT"
      - echo "TF Command: $TF_COMMAND"
      - echo "Initializing Terraform..."
      - terraform init -reconfigure
      - echo "Validating Terraform configuration..."
      - terraform validate
      - echo "Terraform validation completed"
      
  build:
    commands:
      - echo "=== ALR Infrastructure Pipeline - Build Phase ==="
      - echo "Running Terraform $TF_COMMAND for ALR Subscription infrastructure..."
      - |
        case "$TF_COMMAND" in
          "plan")
            echo "Creating Terraform plan..."
            terraform plan -var="environment=$ENVIRONMENT" -out=tfplan
            echo "Terraform plan created successfully"
            ;;
          "apply")
            echo "Applying Terraform configuration..."
            terraform apply -var="environment=$ENVIRONMENT" -auto-approve
            echo "Infrastructure provisioning completed"
            ;;
          "destroy")
            echo "Destroying Terraform infrastructure..."
            terraform destroy -var="environment=$ENVIRONMENT" -auto-approve
            echo "Infrastructure destruction completed"
            ;;
          *)
            echo "Unknown TF_COMMAND: $TF_COMMAND"
            exit 1
            ;;
        esac
      
  post_build:
    commands:
      - echo "=== ALR Infrastructure Pipeline - Post-build Phase ==="
      - echo "Terraform $TF_COMMAND completed successfully on $(date)"
      - echo "Infrastructure components provisioned:"
      - echo "  - Subnets and Route Tables"
      - echo "  - Security Groups"
      - echo "  - NAT Gateway"
      - echo "  - ECR Repository"
      - echo "  - Application Load Balancer"
      - echo "  - IAM Roles"
      - echo "  - Parameter Store values for Application Pipeline"

artifacts:
  files:
    - tfplan
    - '**/*'
  name: alr-infra-pipeline-artifacts
  discard-paths: no