version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
  
  pre_build:
    commands:
      - echo "Terraform $TF_COMMAND started on `date`"
      - cd terraform
      - terraform init -backend-config="bucket=${ENVIRONMENT}-vlt-subscription-terraform-state" -backend-config="key=terraform.tfstate" -backend-config="region=us-west-2"
      - terraform workspace select ${ENVIRONMENT} || terraform workspace new ${ENVIRONMENT}
  
  build:
    commands:
      - |
        if [ "$TF_COMMAND" = "plan" ]; then
          terraform plan -var-file=environments/${ENVIRONMENT}.tfvars -out=tfplan
        elif [ "$TF_COMMAND" = "apply" ]; then
          terraform apply -auto-approve -var-file=environments/${ENVIRONMENT}.tfvars
        else
          echo "Invalid TF_COMMAND: $TF_COMMAND"
          exit 1
        fi

  post_build:
    commands:
      - echo "Terraform $TF_COMMAND completed on `date`"

artifacts:
  files:
    - terraform/tfplan
    - terraform/**/*