AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Terraform execution role'

Parameters:
  Environment:
    Type: String
    Default: usdev-usw2
    AllowedValues:
      - usdev-usw2
      - usqa-usw2
      - usstg-usw2
      - usprod-usw2
      - usbeta-usw2
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: vlt-subscription
    Description: Project name used for resource naming

Resources:
  TerraformExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-vlt-tf-subscription-microservices-terraform-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        # VPC permissions
        - PolicyName: TerraformVPCPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:CreateRouteTable
                  - ec2:DeleteRouteTable
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:AssociateRouteTable
                  - ec2:DisassociateRouteTable
                  - ec2:CreateInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:AttachInternetGateway
                  - ec2:DetachInternetGateway
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                  - ec2:AllocateAddress
                  - ec2:ReleaseAddress
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeRouteTables
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeNatGateways
                  - ec2:DescribeAddresses
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: '*'
                
        # Security Group permissions
        - PolicyName: TerraformSecurityGroupPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:DescribeSecurityGroups
                Resource: '*'
                
        # ECR permissions
        - PolicyName: TerraformECRPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:CreateRepository
                  - ecr:DeleteRepository
                  - ecr:PutLifecyclePolicy
                  - ecr:DeleteLifecyclePolicy
                  - ecr:GetLifecyclePolicy
                  - ecr:DescribeRepositories
                  - ecr:TagResource
                  - ecr:UntagResource
                Resource: !Sub 'arn:aws:ecr:*:${AWS::AccountId}:repository/${Environment}-vlt-*'
                
        # ECS permissions
        - PolicyName: TerraformECSPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - ecs:DeleteCluster
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition
                  - ecs:CreateService
                  - ecs:DeleteService
                  - ecs:UpdateService
                  - ecs:DescribeClusters
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:TagResource
                  - ecs:UntagResource
                Resource: '*'
                
        # ALB permissions
        - PolicyName: TerraformALBPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateLoadBalancer
                  - elasticloadbalancing:DeleteLoadBalancer
                  - elasticloadbalancing:CreateTargetGroup
                  - elasticloadbalancing:DeleteTargetGroup
                  - elasticloadbalancing:CreateListener
                  - elasticloadbalancing:DeleteListener
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:AddTags
                  - elasticloadbalancing:RemoveTags
                Resource: '*'
                
        # API Gateway permissions
        - PolicyName: TerraformAPIGatewayPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                  - apigateway:PATCH
                Resource: '*'
                
        # CloudWatch permissions
        - PolicyName: TerraformCloudWatchPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                  - logs:DescribeLogGroups
                  - logs:TagResource
                  - logs:UntagResource
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:TagResource
                  - cloudwatch:UntagResource
                Resource: '*'
                
        # IAM permissions (limited)
        - PolicyName: TerraformIAMPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${Environment}-vlt-*'
                
        # Terraform state management
        - PolicyName: TerraformStateManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${Environment}-${ProjectName}-terraform-state'
                  - !Sub 'arn:aws:s3:::${Environment}-${ProjectName}-terraform-state/*'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:*:${AWS::AccountId}:table/terraform-state-lock'
      Tags:
        - Key: ohi:project
          Value: vlt
        - Key: ohi:application
          Value: vlt-subscription
        - Key: ohi:module
          Value: vlt-subscription-be
        - Key: ohi:environment
          Value: !Ref Environment

Outputs:
  TerraformRoleArn:
    Description: ARN of the Terraform execution role
    Value: !GetAtt TerraformExecutionRole.Arn